Feature/lp hourly summarizer
fluidefi/fluidefi-caspernet-analytics-tools pull request #4
Opened 2023-02-19 09:46 UTC by MessaoudAzidane

### Summary of changes:
- Added hourlySummarizer class with all summarizations as methods

### Steps for testing: 
- You should have already some test data from the previous services (aggregator) 
- Create `hourly_data` table by running this SQL DDL query 
```
CREATE TABLE hourly_data (
    id SERIAL PRIMARY KEY,
    address VARCHAR(100) NOT NULL,
    open_timestamp_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    close_timestamp_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    close_reserves_0 DOUBLE PRECISION NOT NULL,
    close_reserves_1 DOUBLE PRECISION NOT NULL,
    num_swaps_0 BIGINT NOT NULL,
    num_swaps_1 BIGINT NOT NULL,
    num_mints BIGINT NOT NULL,
    num_burns BIGINT NOT NULL,
    mints_0 DOUBLE PRECISION NOT NULL,
    mints_1 DOUBLE PRECISION NOT NULL,
    burns_0 DOUBLE PRECISION NOT NULL,
    burns_1 DOUBLE PRECISION NOT NULL,
    volume_0 DOUBLE PRECISION NOT NULL,
    volume_1 DOUBLE PRECISION NOT NULL,
    max_block INTEGER NOT NULL,
    close_lp_token_supply NUMERIC(155, 0) NOT NULL
);
```
- Run the main.py:
`python main.py`

### Next step 
- write clean unit tests

2023-02-20 10:56 UTC, AhmadPhazeRo commented on cspr_summarization/services/lp_hourly_summarizer.py
> +from cspr_summarization.entities.Blocks import *
name the imported object

2023-02-20 10:57 UTC, AhmadPhazeRo commented on cspr_summarization/services/lp_hourly_summarizer.py
> +    blocks = Blocks.objects.filter(timestamp_utc__range=(self.start_hour, self.end_hour)).values('block_number', 'timestamp_utc').order_by('-timestamp_utc')
split to seperate lines

2023-02-20 10:59 UTC, AhmadPhazeRo commented on cspr_summarization/services/lp_hourly_summarizer.py
> +    for index, pair in self.all_pairs.iterrows():
suggestion (not required): can do this in parallel

2023-02-20 11:01 UTC, AhmadPhazeRo requested changes
a few simple modifications. Thank you

2023-02-20 14:16 UTC, AhmadPhazeRo approved these changes

2023-02-23 13:10 UTC, AhmadPhazeRo approved these changes
code style LGTM

2023-02-26 11:57 UTC, specialistvlad approved these changes

2023-02-26 14:10 UTC, AhmadPhazeRo reviewed
Stylistically LGTM but have not run yet

2023-03-01 07:49 UTC, AhmadPhazeRo commented
suggestion, but not required, since this is the best time to use the following recommendations given the code is in it's initial phase:
[black ](https://black.readthedocs.io/en/stable/getting_started.html) for formatting code (simple pip install, DON'T add to requirements though since this is for your own usage)
[isort ](https://pycqa.github.io/isort/) for sorting the imports within the file(s) (simple pip install, DON'T add to requirements though since this is for your own usage)

2023-03-01 15:18 UTC, specialistvlad commented
Closing because #6 contains these changes

2023-03-01 15:18 UTC, closed without merging